{
    'name': 'Campus Core (University ERP)',
    'version': '17.0.1.0.0',
    'summary': 'Core Module for University ERP (SIAKAD)',
    'description': 'Master Facilities, Institutions, KRS Management, and Smart Scheduling.',
    'category': 'Education',
    'author': 'Odoo 17 Senior Technical Consultant',
    'website': 'https://www.example.com',
    'depends': ['base', 'hr', 'mail'],
    'data': [
        'security/campus_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/res_partner_views.xml',
        'views/campus_facility_views.xml',
        'views/academic_institution_views.xml',
        'views/academic_krs_views.xml',
        'views/academic_khs_views.xml',
        'views/academic_class_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
